---
title           : "Preregistration of Evaluating bundles of numbers 3"
shorttitle      : "experiment3"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Simon Farrell
    affiliation : 1
  - name        : Geoff Ward
    affiliation : 2
  - name        : Mark Hurlstone
    affiliation : 1
  - name        : Gordon D A Brown
    affiliation : 3
  - name        : Alice Mason
    affiliation : 1

affiliation:
  - id          : 1
    institution : University of Western Australia
  - id          : 2
    institution : University of Essex
  - id          : 3
    institution : University of Warwick

output: prereg::cos_prereg
---

# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. -->

Evaluating bundles of numbers 3


## Research questions
<!-- Please list each research question included in this study. -->

* How does the position of a value in a sequence determine evaluation of that sequence?
* To what extent does memory predict sequence evaluation?


## Hypotheses
<!-- For each of the research questions listed in the previous section, provide one or multiple specific and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. -->

1. Recalled information is a better predictor of evaluation than presented information (i.e., the entire sequence)


# Sampling Plan
<!-- Please describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->

60 participants will be recruited via Prolific Academic to participate in the experiment online. The inclusion criteria are

* Age > 18 and < 65
* Prolific Academic approval rate > 90%
* Country of residence is UK, USA, Ireland, Australia, New Zealand or Canada
* English as first language (self-report)
* Haven't completed previous experiments in this series

## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact the Center for Open Science if you have questions about how to answer this questions (prereg@cos.io). -->

**Registration prior to creation of data**. As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized.


## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that don't include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use. -->

60 participants will be recruited via Prolific Academic to participate in the experiment online. The inclusion criteria are

* Age > 18 and < 65
* Prolific Academic approval rate > 90%
* Country of residence is UK, USA, Ireland, Australia, New Zealand or Canada
* English as first language (self-report)
* Haven't completed previous experiments in this series

Study is expected to be completed in less than 3 days.

## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? -->

60 people


## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. -->

Initial sample size is arbitrary, based on money considerations. (Bayesian statistics mean power analysis is inappropriate)

## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. -->

Data will be analysed after collecting 60 participants. If key Bayes Factors are not sufficiently diagnostic (BF>0.1 and BF<10) further batches of 10 participants will be run and analysed to a maximum of 100 participants (an upper limit imposed by money constraints)

# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->

* Task (recall vs evaluate)
* Serial position of items

## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. For observational studies and meta-analyses, simply state that this is not applicable. -->

* Task (recall vs evaluate)
* Task order (recall and then evaluate, vs evaluate and then recall), post-cued

## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study. -->

* Which items from the list were recalled (i.e., items from which serial positions on the presented sequence)
* Maximum price willing to pay

## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section. -->

Lag-CRP functions will be constructed for each participant following the description in Kahana (1996)

Kahana, M. J. (1996). Associative retrieval processes in free recall. Memory & Cognition, 24, 103-109. 

These will be calculated overall, and conditional on correct initial recall of the highlighted item

# Design Plan
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->


## Study type

**Experiment**. A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.


## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Mark all that apply. -->

No blinding is involved in this study. YES

For studies that involve human subjects, they will not know the treatment group to which they have been assigned. YES

Personnel who interact directly with the study subjects (either human or non-human subjects) will not be aware of the assigned treatments. (N/A)

Personnel who analyze the data collected from the study are not aware of the treatment applied to any given group. NO: manipulated factors will be named in the data file


## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies. -->

All factors are manipulated factorially within-subjects. 


## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? -->

Trials from each cell of the task x serial position factorial will be randomly intermixed. The values on each list are randomly generated.


# Analysis Plan
<!-- For some studies, you may only want to preregister a single confirmatory analysis. For others, there may be multiple sets of confirmatory analyses you wish to register. If you wish to register more than one analysis set, you may do so. If subsequent analyses are very similar to previous ones, you may copy their content and then edit accordingly. Remember, all analyses specified in this section must be reported in the final article, and analyses not specified in this section that are reported in the paper must be clearly labeled as exploratory.

To help you keep track of multiple analyses, you may label each for your reference. -->


## Statistical models
<!-- What statistical model(s) will you use to test your hypothesis(ses)? Please include the type of model (e.g. ANOVA, regression, SEM, etc.) as well as the specification of the model (i.e. what variables will be included). Refer to the *variables* section and include the manipulated or measured variables in the description of the predictors, outcomes, and relevant covariates for the analysis. -->

### Recall analysis

* A mixed effects logistic regression predicting recall probability from serial position and task order. Effects will be assessed using Bayes Factors.
* A lag-CRP function [Kahana, M. J. (1996). Associative retrieval processes in free recall. Memory & Cognition, 24, 103-109. ] will be calculated for each participant in each condition. These will be subject to an ANOVA, the effect of lag being assessed using a Bayes Factor.

### Evaluation analysis

* The evaluation will be predicted from the values at each serial position. 
* Posteriors on the regression coefficients will be obtained using a hierarchical Bayesian analysis.

### Joint analysis

* Memory and evaluations will be jointly fit using a hierarchical Bayesian model. Evaluations will be predicted from presented or recalled values on a trial-by-trial basis. Under one model, evaluations are predicted from the average of all presented values on a trial; under the other they are predicted from the average of all values recalled by that participant on that trial.
* A secondary analysis will examine whether the memory-evaluation relationship in previous analysis is modulated by task order.

## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. -->

N/A

## Follow-up analyses
<!-- If not specified previously, will you be conducting any confirmatory analyses to follow up on effects in your statistical model, such as subgroup analyses, pairwise or complex contrasts, or follow-up tests from interactions. Remember that any analyses not specified in this research plan must be noted as exploratory. -->

None


## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information you'll use (e.g. p-values, Bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this? -->

Bayes Factors, or posteriors on model parameter estimates, will be used to perform inference.


## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? -->

* Participants will be excluded if they do not meet the following criteria:
  * At least 80% of trials are completed
  * At least one item is correctly recalled on average in memory task

## Missing data
<!-- How will you deal with incomplete or missing data? -->

For mixed effects modelling and Bayesian modelling, missing data will not present a major issue under criterion of 80% complete data set per participant. For the Bayesian ANOVA, participants with missing cells will be omitted from the analysis.

# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
